[package]
name = "scratch-git"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "src/server/main.rs"
name = "scratch-git"

[dependencies]
rocket = { version = "0.5.0", features = ["json"] }
serde_json = "1.0.113"
zip-extract = "0.1.3"
lazy_static = "1.4.0"