[package]
name = "scratch-git"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "src/server/main.rs"
name = "scratch-git"

[dependencies]
rocket = { version = "0.5.0", features = ["json"] }
rocket_cors = { version = "0.6.0", default_features = false }
serde_json = "1.0.113"
serde = "1.0.196"
zip = { version = "0.6.6", default-features = false, features = ["deflate"] }