[package]
name = "scratch-git"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "src/server/main.rs"
name = "scratch-git"

[dependencies]
rocket = "0.5.0"
serde_json = "1.0.113"
zip-extract = { version = "0.1.3", default_features = false, features = ["deflate"] }
